title: Troy Tsubota
email: troy (dot) tsubota (at) gmail (dot) com
description: >-

url: https://tktsubota.github.io
twitter_username: tktsubota
github_username: tktsubota

permalink: /:title/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
